version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=campusUsername
      - POSTGRES_PASSWORD=campusPassword
      - POSTGRES_DB=campus_db
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5433:5432
    volumes:
      - ./data/postgres:/data/postgres
    container_name: db_postgres
volumes:
  data:
    driver: local
networks:
  local:
    driver: bridge
